# Generated by Django 5.2 on 2025-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='sn',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
