# Generated by Django 5.2 on 2025-12-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_student_id_student_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sn',
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
